nc: 80
end2end: true
scales:
  n:
  - 0.5
  - 0.25
  - 1024
  s:
  - 0.5
  - 0.5
  - 1024
  m:
  - 0.5
  - 1.0
  - 512
  l:
  - 1.0
  - 1.0
  - 512
  x:
  - 1.0
  - 1.5
  - 512
backbone:
- - -1
  - 1
  - Conv
  - - 64
    - 3
    - 2
- - -1
  - 1
  - Conv
  - - 128
    - 3
    - 2
- - -1
  - 1
  - C3k2
  - - 256
    - false
    - 0.25
- - -1
  - 1
  - CenterRankConv
  - - 256
    - 3
    - 2
    - 0.25
- - -1
  - 1
  - C3k2_OrthoRank
  - - 512
    - false
    - 0.25
    - 1
    - true
    - 0.25
- - -1
  - 1
  - CenterRankConv
  - - 512
    - 3
    - 2
    - 0.25
- - -1
  - 1
  - C3k2_OrthoRank
  - - 512
    - true
    - 0.5
    - 1
    - true
    - 0.25
- - -1
  - 1
  - CenterRankConv
  - - 1024
    - 3
    - 2
    - 0.25
- - -1
  - 1
  - C3k2_OrthoRank
  - - 1024
    - false
    - 0.25
    - 1
    - true
    - 0.25
- - -1
  - 1
  - SPPF
  - - 1024
    - 5
- - -1
  - 1
  - SimAM
  - []
head:
- - - 6
    - 10
  - 1
  - OSIFusion
  - - 512
- - -1
  - 1
  - C3k2_OrthoRank
  - - 512
    - false
    - 0.25
    - 1
    - true
    - 0.25
- - - 4
    - 12
  - 1
  - OSIFusion
  - - 256
- - -1
  - 1
  - C3k2_OrthoRank
  - - 256
    - false
    - 0.375
    - 1
    - true
    - 0.25
- - -1
  - 1
  - CenterRankConv
  - - 256
    - 3
    - 2
    - 0.25
- - - 12
    - 15
  - 1
  - OSIFusion
  - - 512
- - -1
  - 1
  - C3k2_OrthoRank
  - - 512
    - false
    - 0.25
    - 1
    - true
    - 0.25
- - -1
  - 1
  - CenterRankConv
  - - 512
    - 3
    - 2
    - 0.25
- - - 10
    - 18
  - 1
  - OSIFusion
  - - 1024
- - -1
  - 1
  - C3k2_OrthoRank
  - - 1024
    - false
    - 0.25
    - 1
    - true
    - 0.25
- - - 14
    - 17
    - 20
  - 1
  - OrthoRankDetect
  - - nc
    - 0.25
scale: n
