"""CPU baseline profiling and regression probes, without editing Ultralytics.

FLOPs count Conv2d multiply/add and Attention's two matrix products only.
Output storage footprints are NOT peak activation memory or DRAM traffic.
"""
from __future__ import annotations

import argparse
from copy import deepcopy
import hashlib
import json
from pathlib import Path
import statistics
import sys
import time

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))


def distribution(samples):
    import numpy as np
    return dict(mean_ms=statistics.mean(samples), median_ms=statistics.median(samples),
                p95_ms=float(np.percentile(samples, 95)), fps=1000 / statistics.mean(samples), samples_ms=samples)


def footprint(value):
    import torch
    storages = {}

    def visit(x):
        if isinstance(x, torch.Tensor):
            storage = x.untyped_storage()
            storages[storage.data_ptr()] = storage.nbytes()
        elif isinstance(x, dict):
            for child in x.values():
                visit(child)
        elif isinstance(x, (list, tuple)):
            for child in x:
                visit(child)
    visit(value)
    return sum(storages.values())


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--reference', type=Path, default=ROOT / 'experiments/exp000_audit/baseline_reference.pt')
    parser.add_argument('--output', type=Path, default=ROOT / 'experiments/exp000_audit')
    args = parser.parse_args()
    args.output.mkdir(parents=True, exist_ok=True)
    import torch
    from ultralytics.nn.modules.block import Attention
    from ultralytics.nn.tasks import DetectionModel
    from ultralytics.cfg import get_cfg

    torch.set_num_threads(1)
    torch.manual_seed(0)
    # Only load the local tensor/config snapshot generated by audit_baseline.py.
    ref = torch.load(args.reference, map_location='cpu', weights_only=True)
    model = DetectionModel(deepcopy(ref['config']), verbose=False).eval()
    model.load_state_dict(ref['state_dict'], strict=True)
    x = ref['input']
    with torch.inference_mode():
        original = model(x)[0]
    torch.testing.assert_close(original, ref['output'], rtol=0, atol=0)
    tests = {'reference_roundtrip_exact': True, 'cuda': 'SKIP: torch is CPU-only', 'cuda_amp': 'SKIP: torch is CPU-only'}

    rows, handles, primitive = [], [], []
    for index, stage in enumerate(model.model):
        row = dict(index=index, module=type(stage).__name__, parameters=sum(p.numel() for p in stage.parameters()),
                   conv_matmul_flops=0, output_storage_bytes=0)
        rows.append(row)
        for name, module in stage.named_modules():
            if isinstance(module, (torch.nn.Conv2d, Attention)):
                def counter(m, inputs, output, row=row, name=name):
                    if isinstance(m, torch.nn.Conv2d):
                        flops = 2 * output.numel() * (m.in_channels // m.groups) * m.kernel_size[0] * m.kernel_size[1]
                    else:
                        b, _, h, w = inputs[0].shape
                        flops = 2 * b * m.num_heads * (h*w)**2 * (m.key_dim + m.head_dim)
                    row['conv_matmul_flops'] += flops
                    primitive.append(dict(name=f"model.{row['index']}.{name}", module=type(m).__name__, flops=flops))
                handles.append(module.register_forward_hook(counter))
        def storage_hook(m, inputs, output, row=row):
            row['output_storage_bytes'] = footprint(output)
        handles.append(stage.register_forward_hook(storage_hook))
    with torch.inference_mode():
        model(x)
    for handle in handles:
        handle.remove()

    # Wall-clock stage samples include module execution and hook dispatch overhead.
    handles, started = [], {}
    for index, stage in enumerate(model.model):
        rows[index]['wall_ms_samples'] = []
        def before(m, inputs, index=index):
            started[index] = time.perf_counter_ns()
        def after(m, inputs, output, index=index):
            rows[index]['wall_ms_samples'].append((time.perf_counter_ns() - started[index]) / 1e6)
        handles.extend([stage.register_forward_pre_hook(before), stage.register_forward_hook(after)])
    with torch.inference_mode():
        for _ in range(20):
            model(x)
    for handle in handles:
        handle.remove()
    for row in rows:
        row['wall_time'] = distribution(row.pop('wall_ms_samples'))

    latency = {}
    for name, current in [('unfused', model), ('fused', deepcopy(model).fuse(verbose=False))]:
        with torch.inference_mode():
            actual = current(x)[0]
            torch.testing.assert_close(actual, original, rtol=1e-4, atol=1e-4)
            for _ in range(10):
                current(x)
            samples = []
            for _ in range(50):
                start = time.perf_counter_ns()
                current(x)
                samples.append((time.perf_counter_ns() - start) / 1e6)
        latency[name] = dict(**distribution(samples), warmup=10,
                             parameters=sum(p.numel() for p in current.parameters()),
                             maximum_absolute_output_error=float((actual-original).abs().max()))
    tests['standard_fuse_equivalence'] = True

    # Verify baseline training contract and real detection loss on nonempty targets.
    training = deepcopy(model).train()
    training.args = get_cfg()
    batch = dict(img=torch.rand(2, 3, 64, 96), batch_idx=torch.tensor([0., 1.]),
                 cls=torch.tensor([[0.], [1.]]), bboxes=torch.tensor([[.5,.5,.5,.5],[.4,.4,.3,.3]]))
    losses, detached = training(batch)
    assert torch.isfinite(losses).all() and torch.isfinite(detached).all()
    losses.sum().backward()
    gradients = [p.grad for p in training.parameters() if p.requires_grad]
    assert all(g is not None and torch.isfinite(g).all() for g in gradients)
    assert any(torch.count_nonzero(g) for g in gradients)
    tests['batch2_rectangular_forward_loss_backward_finite'] = True
    tests['loss_components_synthetic_only'] = detached.tolist()
    tests['trainable_parameters_with_gradient'] = len(gradients)

    # Quantify the isolated constructor difference, not a proposed module.
    sppf = deepcopy(model.model[9]).eval()
    release_style = deepcopy(sppf)
    release_style.cv1.act = torch.nn.SiLU()
    feature = torch.randn(2, sppf.cv1.conv.in_channels, 19, 21)
    with torch.inference_mode():
        a, b = sppf(feature), release_style(feature)
    tests['sppf_activation_only_probe'] = dict(max_abs_error=float((a-b).abs().max()),
                                              input_shape=list(feature.shape), equal=bool(torch.equal(a,b)),
                                              note='Same local SPPF weights; change cv1 activation on copy only. Not full upstream equivalence test.')

    # CPU operator attribution, separate from uninstrumented latency.
    with torch.profiler.profile(activities=[torch.profiler.ProfilerActivity.CPU], record_shapes=True,
                                profile_memory=True, with_flops=True) as prof:
        with torch.inference_mode():
            model(x)
    operators = [dict(name=e.key, calls=e.count, self_cpu_time_us=e.self_cpu_time_total,
                      self_cpu_memory_bytes=e.self_cpu_memory_usage, supported_flops=e.flops)
                 for e in prof.key_averages()]
    (args.output / 'cpu_operators.json').write_text(json.dumps(operators, indent=2), encoding='utf-8')
    checksums = {}
    inventory = json.loads((args.reference.parent / 'source_inventory.json').read_text(encoding='utf-8'))
    for entry in inventory['files']:
        if entry['path'].startswith('ultralytics/'):
            path = ROOT / entry['path']
            checksums[entry['path']] = hashlib.sha256(path.read_bytes()).hexdigest() == entry['sha256']
    assert all(checksums.values()), 'An original source/config changed since initial audit'
    tests['original_source_config_hashes_unchanged'] = len(checksums)
    result = dict(device='cpu', precision='FP32', batch=1, imgsz=[640,640], threads=1, trained=False,
                  stages=rows, primitive_flops=primitive, latency=latency, tests=tests,
                  gpu_kernel_time=None, gpu_peak_memory=None, dram_bandwidth=None, peak_cpu_activation_memory=None,
                  total_conv_matmul_gflops=sum(r['conv_matmul_flops'] for r in rows)/1e9,
                  scope='2 FLOPs per MAC; Conv2d and Attention matmuls. Excludes BN, activation, softmax, pooling, resize, concat, decode/NMS arithmetic. Storage footprint is not peak or bandwidth.')
    (args.output / 'profile.json').write_text(json.dumps(result, indent=2), encoding='utf-8')
    print(json.dumps(dict(gflops=result['total_conv_matmul_gflops'], tests=tests,
                         latency={k:{q:v[q] for q in ['mean_ms','median_ms','p95_ms','fps']} for k,v in latency.items()}), indent=2))


if __name__ == '__main__':
    main()
